name: Terraform CI

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Verify Terraform
        run: terraform version
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config=environments/dev/backend.hcl \
            -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -input=false